// generated by Neptune Namespaces v4.x.x
// file: perfs/index.js

(module.exports = require('./namespace'))

.addModules({
  Baseline: require('./baseline'),
  Data:     require('./data')
});
require('./iterationV3');