// generated by Neptune Namespaces v4.x.x
// file: perfs/namespace.js

module.exports = require('neptune-namespaces').addNamespace(
  'Perfs',
  (class Perfs extends Neptune.PackageNamespace {})
  ._configureNamespace(require('../../package.json'))
);
require('./iterationV3/namespace');