// generated by Neptune Namespaces v4.x.x
// file: perfs/iterationV3/index.js

(module.exports = require('./namespace'))

.addModules({
  Each:           require('./each'),
  ObjectSource:   require('./objectSource'),
  StandardImport: require('./StandardImport')
});