// generated by Neptune Namespaces v4.x.x
// file: perfs/iterationV3/namespace.js

module.exports = require('../namespace').addNamespace(
  'IterationV3',
  class IterationV3 extends Neptune.PackageNamespace {}
);
